### ISSUE TITLE
.net 4.7 + windows build 17017 + iisexpress: crashing with Access Violation in IsLocalRequest call

### ISSUE THREAD

**Issue by kbalint** [Microsoft/dotnet#523]
hi, I don't know where to report it: my working dev config got bombed. With this windows build, something went haywire, as the IsLocalRequest call throws an exception.  I've tried to debug it, but can't find any pdb-s  for this function. See more here: https://stackoverflow.com/questions/46785414/iisexpress-exe-started-crashing-with-access-violation-in-islocalrequest-call

questions: 
0) what could cause this error? does anyone have access to the source code?
1) where to report windows dev build regressions?
2) where to report iisexpress exceptions?
3) why no pdb-s on the MS symbols server for iisexpress?

thanks!

**Comment by DamianEdwards** [comment]
@shirhatti

**Comment by shirhatti** [comment]
@kbalint There was an HTTP.SYS driver level regression in the Windows Insider Build 17017. This breaks all consumers of HTTP.SYS like IIS and IIS Express. We're doing our best right now to fast track a fix in time for the next insiders build.

1.  The official way to report Windows Dev build regression is via the Feedback Hub app
2. You can report IIS Express issues via https://developercommunity.visualstudio.com/
3. I'm not sure about the symbols- let me get back to you on that

**Comment by shirhatti** [comment]
Update: I just checked with the team and we have made a conscious decision not to publish IIS Express symbols publicly. We may re-visit this decision in the future, but as it stands today we don't plan to publish the symbols.

**Comment by kbalint** [comment]
@shirhatti: thanks for the information.

**Comment by kbalint** [comment]
@shirhatti I got a new build for another machine, win insider fast 17025 - 171020-1626. has the regression been fixed in this build? thanks

**Comment by shirhatti** [comment]
Yes, it has been fixed in 17025.1000.rs_prerelease.171020-1626.

**Comment by jamescarter-le** [comment]
Can I ask if this has leaked into a non-Insider build?

I am running 10.0.16299, and my application which was previously working fine in IIS Express now gives me an access violation shortly after clients connect. I cannot find the exact cause because the exception is in an unmanaged thread in iiscore.dll which I cannot find Symbols for.

I have reverted my source repository back to 3 weeks ago when this issue definitely was not present and the issue persists - I have no AV enabled and Windows Defender is disabled through Group Policy. I have been battling this exception for about 1 week.

```
Loading Dump File [C:\Users\James Carter\AppData\Local\CrashDumps\iisexpress.exe.19984.dmp]

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 55b76364 (compdyn!RegisterModule+0x00003f44)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000068
Attempt to read from address 00000068

PROBLEM_CLASSES:
    ID:     [0n301]
    Type:   [@ACCESS_VIOLATION]
    Class:  Addendum
    Scope:  BUCKET_ID
    Name:   Omit
    Data:   Omit
    PID:    [Unspecified]
    TID:    [0x4554]
    Frame:  [0] : compdyn!RegisterModule

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
0783f698 55b74b04 00000001 0783f6d0 07593c80 compdyn!RegisterModule+0x3f44
0783f6bc 55b72613 073709d4 55b71008 294f81dc compdyn!RegisterModule+0x26e4
0783f6e0 55b72776 07593c80 294f823c 0783f76c compdyn!RegisterModule+0x1f3
0783f6f4 56326e91 07593c80 20000000 00000000 compdyn!RegisterModule+0x356
0783f720 56326313 073709d4 07593c80 0783f76c iiscore+0x26e91
0783f7b0 563151cb 00000001 00000000 00000000 iiscore+0x26313
0783f7fc 5631d004 00000001 00000000 00000000 iiscore+0x151cb
0783f840 56319a88 00000000 00000000 00000000 iiscore+0x1d004
0783f868 56318bdd 00000000 00000000 00000000 iiscore+0x19a88
0783f884 596532ce 00000000 00000000 073f6f90 iiscore+0x18bdd
0783f8b8 596531db 59650000 596531b0 0738efd0 w3tp!THREAD_POOL::PostCompletion+0x14e
0783f8d8 596520a7 07391a68 59652040 59652040 w3tp!THREAD_POOL::PostCompletion+0x5b
0783f8f8 74288654 0738efd0 74288630 cf2fd6cd w3tp+0x20a7
0783f90c 77754a47 0738efd0 a3a00235 00000000 kernel32!BaseThreadInitThunk+0x24
0783f954 77754a17 ffffffff 77779ee4 00000000 ntdll!__RtlUserThreadStart+0x2f
0783f964 00000000 59652040 0738efd0 00000000 ntdll!_RtlUserThreadStart+0x1b

```

**Comment by Zapnologica** [comment]
How do we got hold of this fixed release? I have so much trouble debugging my applications, ISS express just crashes with the access violation error all the time. I have updated Visual studio to the latest when ever there is an update and still getting the error., Is there a way to update iis express by its self?

**Comment by kbalint** [comment]
@Zapnologica I had a failed SSD, I needed to do a clean install since, and it's OK for me now. I advise you to do the same.
